import os
import streamlit as st

# from dotenv import load_dotenv

# load_dotenv()


# AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")

# AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")

# AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")

# AZURE_OPENAI_CHAT_DEPLOYMENT = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT")

AZURE_OPENAI_ENDPOINT = st.secrets["AZURE_OPENAI_ENDPOINT"]

AZURE_OPENAI_KEY = st.secrets["AZURE_OPENAI_KEY"]

AZURE_OPENAI_API_VERSION = st.secrets["AZURE_OPENAI_API_VERSION"]

AZURE_OPENAI_CHAT_DEPLOYMENT = st.secrets["AZURE_OPENAI_CHAT_DEPLOYMENT"]

# EMBEDDING_DEPLOYMENT = os.getenv(
#     "AZURE_OPENAI_EMBEDDING_DEPLOYMENT"
# )
